name: UI Tests
on: [push, pull_request]
jobs:
  ui_test:
    name: UI Tests
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ps-version:
          - '8.0.5' 
          - '8.1.3'
          - 'nightly'
    env:
      PS_VERSION: ${{ matrix.ps-version }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3.1.0

      - uses: actions/setup-node@v3
        with:
          node-version: 14

      - name: Build 
        run: npm install && npm run build

      - name: Start containers
        run: docker-compose -f "docker-compose.yml" up -d --build
      
      - name: Install dependencies
        run: npm ci
        working-directory: tests/UI/

      - name: Install Playwright Browsers
        run: npx playwright install --with-deps
        working-directory: tests/UI/

      - name: Run Playwright tests
        run: npx playwright test
        working-directory: tests/UI/

      - uses: actions/upload-artifact@v3
        if: always()
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30